step1 = startString.replace(string1,string2)
print(step1)
step2 = step1.replace(string6,string7)
print(step2)
step3 = step2.replace(string2, string1)
print(step3)
step4 = step3.replace(string10, string3)
print(step4)
step5 = step4.replace(string8, string5)
print(step5)